### ISSUE TITLE
Hide Explore button

### ISSUE THREAD

**Issue by vincentpun** [patrickshox/Focus-for-YouTube#12]
I find that the Explore button in the sidebar can easily send me into a rabbit hole. DF YouTube fore Chrome and Firefox has the ability to hide the button, and it'll be great if Focus for YouTube has it as well!

**Comment by hish85** [comment]
Yip! This one would be great!

**Comment by jfk3505** [comment]
+1 on this one. I wrote an app store review with this exact comment

**Comment by patrickshox** [comment]
Great idea! Commit 866af3dc83cdb3d545b3d8dce62a4431930e34a0 will resolve this. You'll be able to use this feature in version 2.2 of Focus for YouTube later this week.
