### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by realPengHao** [patrickshox/Focus-for-YouTube#14]
It would be cool to have an option to blur the thumbnails and show the picture when mouseover.

**Comment by patrickshox** [comment]
Wow that's a great idea. And sounds totally doable to implement without asking for additional permission. I'm really busy the next few weeks but that's definitely something I'll put on my todo list.

**Comment by patrickshox** [comment]
2c19d6f addresses this. Showing the image on mouseover would require a content script and thus additional permissions, which I didn't want to do. So I split the difference and just added an option to block all thumbnail images, without the ability to display them on mouseover.
