### ISSUE TITLE
New Suggestion

### ISSUE THREAD

**Issue by user884586730** [patrickshox/Focus-for-YouTube#15]
What would be amazing if there was a way to lock this app with some sort of a unique password. What I mean is like if a user would want to have this Youtube regulation feature turned on and then unable to turn off until a family member/friend puts in the password to unlock the app. This would be so helpful for me while I'm studying, and I think it's an absolutely excellent idea. Let me know if this is possible.

**Comment by patrickshox** [comment]
It sounds impossible as far as I know. Apps can always be deleted, and extensions can always be disabled within the Safari preferences.
