### ISSUE TITLE
Tool bar toggle button

### ISSUE THREAD

**Issue by one70** [patrickshox/Focus-for-YouTube#3]
I think it would be quite useful to have a Safari toolbar button for this extension.

Ideal functionality
Click: toggle the blocklist on and off.
Click-and-hold: display a dropdown menu to quickly customize which items are blocked.

Appearance
A focus icon like this one would be quite elegant:
https://www.flaticon.com/free-icon/focus_635908

Thanks for the great extension! It helps me avoid being sucked in a black hole of distraction when I watch a video on YouTube.

**Comment by patrickshox** [comment]
To include a toolbar icon, I'd need Focus to ask for greater permissions as well as have two panes in the Safari Extension preferences. For that reason, I decided against a toolbar item.
