### ISSUE TITLE
Disable comments section

### ISSUE THREAD

**Issue by stoica94** [patrickshox/Focus-for-YouTube#5]
Comments can also be distracting and I find myself leaving the video in order to see the comments. 

I would definitely enjoy this tool having an option to disable comments.

**Comment by patrickshox** [comment]
That’s an important feature to add. I can begin working on that in a couple weeks.

**Comment by patrickshox** [comment]
Wait lol I think this already exists. Did you know you can scroll down within the app to see all the selectors?
